services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 2160:5432
    environment:
      POSTGRES_PASSWORD: perro_gato_tortuga_loro
      POSTGRES_USER: nzsitsolutions
      POSTGRES_DB: numi
    networks:
      - numi

  cache:
    image: redis:latest
    restart: always
    ports:
      - 6388:6381
    networks:
      - numi

networks:
  numi:
    name: numi_network
